
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 18;
  public static final int CLASS = 2;
  public static final int SEMICOLON = 3;
  public static final int ELSE = 14;
  public static final int NOTEQ = 22;
  public static final int PLUS = 16;
  public static final int OR = 19;
  public static final int RBRACE = 6;
  public static final int RPAREN = 9;
  public static final int INT = 11;
  public static final int BOOLEAN_LITERAL = 24;
  public static final int NOT = 20;
  public static final int IDENTIFIER = 25;
  public static final int RETURN = 15;
  public static final int IF = 13;
  public static final int LPAREN = 8;
  public static final int LBRACE = 5;
  public static final int BOOLEAN = 10;
  public static final int COMMA = 4;
  public static final int MULT = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EQ = 7;
  public static final int INTEGER_LITERAL = 23;
  public static final int EQEQ = 21;
  public static final int VOID = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "SEMICOLON",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "BOOLEAN",
  "INT",
  "VOID",
  "IF",
  "ELSE",
  "RETURN",
  "PLUS",
  "MULT",
  "AND",
  "OR",
  "NOT",
  "EQEQ",
  "NOTEQ",
  "INTEGER_LITERAL",
  "BOOLEAN_LITERAL",
  "IDENTIFIER"
  };
}

